services:
  nginx:
    build:
      context: ./nginx

    restart: unless-stopped

    volumes:
      - ./app/certbot/www/:/var/www/certbot:ro
      - ./app/certbot/letsencrypt:/etc/letsencrypt:ro
      - ./app/nginx/sites-enabled/:/etc/nginx/sites-enabled:ro
      - ./app/nginx/logs:/var/log/nginx

    network_mode: host

  certbot:
    image: certbot/certbot:latest

    depends_on:
      - nginx

    volumes:
      - ./app/certbot/www:/var/www/certbot
      - ./app/certbot/letsencrypt:/etc/letsencrypt
