services:
  nginx:
    build:
      context: ./nginx

    restart: unless-stopped

    volumes:
      - ./app/certbot/www/:/var/www/certbot:ro
      - ./app/nginx/sites-enabled/:/etc/nginx/sites-enabled:ro

    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot:latest

    volumes:
      - ./app/certbot/www:/var/www/certbot:rw
      - ./app/certbot/letsencrypt:/etc/letsencrypt/:rw
